Design Entry;HDL Check||(null)||Checking HDL syntax of 'HW2P7.v'||(null);(null)||(null);(null)
Design Entry;HDL Check||(null)||Syntax checking is successful||(null);(null)||(null);(null)
Design Entry;SmartDesign Check||(null)||SmartDesign 'SF2Project' design rules check succeeded||(null);(null)||(null);(null)
Design Entry;SmartDesign Check||(null)||'SF2Project' was successfully generated.  ||(null);(null)||(null);(null)
HelpInfo,C:\Microsemi\Libero_SoC_v12.6\SynplifyPro\lib\html,fpgahelp.qhc,synerrmsg.mp,C:\Microsemi\Libero_SoC_v12.6\SynplifyPro\bin\assistant
Implementation;Synthesis||FX1184||@N: Applying syn_allowed_resources blockrams=21 on top level netlist HW2P7 ||HW2P7.srr(185);liberoaction://cross_probe/hdl/file/'<project>\synthesis\HW2P7.srr'/linenumber/185||null;null
Implementation;Synthesis||MT530||@W:Found inferred clock HW2P7|CP which controls 5 sequential elements including count_temp[3:0]. This clock has no specified timing constraint which may adversely impact design performance. ||HW2P7.srr(211);liberoaction://cross_probe/hdl/file/'<project>\synthesis\HW2P7.srr'/linenumber/211||hw2p7.v(35);liberoaction://cross_probe/hdl/file/'<project>\hdl\HW2P7.v'/linenumber/35
Implementation;Synthesis||FX1143||@N: Skipping assigning INTERNAL_VREF to iobanks, because the table of mapping from pin to iobank is not initialized.||HW2P7.srr(213);liberoaction://cross_probe/hdl/file/'<project>\synthesis\HW2P7.srr'/linenumber/213||null;null
Implementation;Synthesis||FP130||@N: Promoting Net CP on CLKINT  I_1 ||HW2P7.srr(309);liberoaction://cross_probe/hdl/file/'<project>\synthesis\HW2P7.srr'/linenumber/309||null;null
Implementation;Synthesis||MT420||@W:Found inferred clock HW2P7|CP with period 10.00ns. Please declare a user-defined clock on port CP.||HW2P7.srr(358);liberoaction://cross_probe/hdl/file/'<project>\synthesis\HW2P7.srr'/linenumber/358||null;null
Implementation;Place and Route;RootName:HW2P7
Implementation;Place and Route||(null)||Please refer to the log file for details about 4 Info(s)||HW2P7_layout_log.log;liberoaction://open_report/file/HW2P7_layout_log.log||(null);(null)
